services:
  server:
    build:
      context: .
      dockerfile: MarketData.Api/Dockerfile
      target: final
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: marketdata_sql
    restart: always
    secrets:
      - db-password
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt


